FROM node:13-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app
COPY config.dev.json /usr/src/app/config.json
RUN npm install
ENV NODE_ENV development
ENV PORT 3000
EXPOSE 3000
CMD [ "npm", "run", "dev" ]
